Hello les copains, ce notebook permet de récupérer les latitudes et les longitudes des valeurs manquantes de la base idf_vf_full.parquet !

In [2]:
import pandas as pd
import os

In [3]:
print(os.getcwd())
os.chdir("../")
print(os.getcwd())

/Users/antoninbenard/PycharmProjects/land_value_prediction/notebooks
/Users/antoninbenard/PycharmProjects/land_value_prediction

In [4]:
df = pd.read_parquet("data/processed/idf_vf_full.parquet")

In [5]:
df.head()

,date_mutation,nature_mutation,valeur_fonciere,adresse_numero,adresse_nom_voie,adresse_code_voie,code_postal,code_commune,nom_commune,code_departement,...,commune_part_admin_sante,commune_etablissements_par_menage,commune_taux_etablissements_10_plus,commune_sante_score_2013_commune,commune_education_score_2013_commune,commune_revenu_score_2013_commune,commune_idh2_2013_commune,commune_taux_criminalite_moyen,commune_taux_croissance_pop,commune_densite_pop
0,2021-01-01,Vente,169500.0,28.0,ALL HOCHE,4440,92130.0,92040,Issy-les-Moulineaux,92,...,0.090161,0.075901,0.254014,0.700824,0.835437,0.704796,0.747019,0.376209,1.045371,16106.117647
1,2021-01-02,Vente,415000.0,109.0,RUE DES COURLIS,1570,95100.0,95018,Argenteuil,95,...,0.085686,0.071492,0.182996,0.567644,0.364296,0.331115,0.421018,0.561570,0.784827,6400.116144
2,2021-01-02,Vente,415000.0,109.0,RUE DES COURLIS,1570,95100.0,95018,Argenteuil,95,...,0.085686,0.071492,0.182996,0.567644,0.364296,0.331115,0.421018,0.561570,0.784827,6400.116144
3,2021-01-02,Vente,512000.0,97.0,RUE DE CHARONNE,1888,75011.0,75111,Paris 11e Arrondissement,75,...,0.067020,0.131609,0.145909,0.680558,0.851424,0.607516,0.713166,0.996164,-1.129705,39957.220708
4,2021-01-02,Vente,512000.0,97.0,RUE DE CHARONNE,1888,75011.0,75111,Paris 11e Arrondissement,75,...,0.067020,0.131609,0.145909,0.680558,0.851424,0.607516,0.713166,0.996164,-1.129705,39957.220708

In [6]:
df.shape

(672749, 54)

In [23]:
df_without_lat = df[df['latitude'].isnull()]

In [24]:
df_without_lat['latitude']

38       NaN
150      NaN
214      NaN
250      NaN
361      NaN
          ..
665110   NaN
671427   NaN
671437   NaN
672295   NaN
672297   NaN
Name: latitude, Length: 8580, dtype: float64

In [25]:
df_without_lat['longitude']

38       NaN
150      NaN
214      NaN
250      NaN
361      NaN
          ..
665110   NaN
671427   NaN
671437   NaN
672295   NaN
672297   NaN
Name: longitude, Length: 8580, dtype: float64

In [26]:
df_without_lat.head()

,date_mutation,nature_mutation,valeur_fonciere,adresse_numero,adresse_nom_voie,adresse_code_voie,code_postal,code_commune,nom_commune,code_departement,...,commune_part_admin_sante,commune_etablissements_par_menage,commune_taux_etablissements_10_plus,commune_sante_score_2013_commune,commune_education_score_2013_commune,commune_revenu_score_2013_commune,commune_idh2_2013_commune,commune_taux_criminalite_moyen,commune_taux_croissance_pop,commune_densite_pop
38,2021-01-04,Vente,307000.0,93.0,RUE DE LA BUTTE PINSON,0690,93380.0,93059,Pierrefitte-sur-Seine,93,...,0.072340,0.064359,0.124823,0.591285,0.252541,0.141425,0.328417,NaN,1.584453,8887.390029
150,2021-01-04,Vente,150000.0,17.0,RUE GABRIELLE JOSSERAND,4110,93500.0,93055,Pantin,93,...,0.091778,0.101081,0.200765,0.590577,0.451268,0.222436,0.421427,0.767084,1.824759,11473.453094
214,2021-01-04,Vente,166000.0,51.0,RUE SOMMEVILLE,0960,77380.0,77122,Combs-la-Ville,77,...,0.131222,0.049951,0.203620,0.634375,0.523603,0.531759,0.563245,0.375176,0.334504,1545.787293
250,2021-01-04,Vente,265000.0,7.0,RUE DES ECOLES,0560,91360.0,91216,Épinay-sur-Orge,91,...,0.136000,0.057857,0.148000,0.611611,0.554353,0.626984,0.597650,0.376553,1.787394,2538.288288
361,2021-01-05,Vente,330000.0,10.0,CHE VERT,0120,78113.0,78171,Condé-sur-Vesgre,78,...,0.100000,0.061602,0.033333,0.566286,0.671497,0.642020,0.626601,0.015336,1.021409,112.511671

In [27]:
df_without_lat.columns

Index(['date_mutation', 'nature_mutation', 'valeur_fonciere', 'adresse_numero',
       'adresse_nom_voie', 'adresse_code_voie', 'code_postal', 'code_commune',
       'nom_commune', 'code_departement', 'nombre_lots', 'code_type_local',
       'type_local', 'surface_reelle_bati', 'nombre_pieces_principales',
       'surface_terrain', 'longitude', 'latitude', 'annee', 'semestre',
       'trimestre', 'semestre_precedent', 'annee_precedente',
       'trimestre_precedent', 'prix_m2',
       'commune_prix_median_m2_semestre_prec', 'ecart_prix_median_pct',
       'commune_revenu_median_2020', 'commune_etablissements_agriculture_2021',
       'commune_etablissements_industrie_2021',
       'commune_etablissements_construction_2021',
       'commune_etablissements_1_salarie_2021',
       'commune_etablissements_10_plus_salaries_2021',
       'commune_densite_population_active_2020',
       'commune_taux_residences_secondaires', 'commune_taux_logements_vacants',
       'commune_taux_proprietaires',
       'commune_ratio_residences_secondaires_population',
       'commune_densite_residences_principales_2020',
       'commune_taux_chomage_15_64', 'commune_taux_emploi',
       'commune_evolution_emploi_2014_2020',
       'commune_part_services_entreprises', 'commune_part_commerce_tourisme',
       'commune_part_admin_sante', 'commune_etablissements_par_menage',
       'commune_taux_etablissements_10_plus',
       'commune_sante_score_2013_commune',
       'commune_education_score_2013_commune',
       'commune_revenu_score_2013_commune', 'commune_idh2_2013_commune',
       'commune_taux_criminalite_moyen', 'commune_taux_croissance_pop',
       'commune_densite_pop'],
      dtype='object')

In [28]:
import pandas as pd
import requests
import time
from tqdm import tqdm

def geocoder_adresse(numero, nom_voie, code_postal, commune):
    """
    Géocode une adresse via l'API Géoplateforme
    """
    # Construire l'adresse complète
    adresse_parts = []
    if pd.notna(numero) and str(numero).strip():
        adresse_parts.append(str(numero))
    if pd.notna(nom_voie) and str(nom_voie).strip():
        adresse_parts.append(str(nom_voie))
    if pd.notna(code_postal) and str(code_postal).strip():
        adresse_parts.append(str(code_postal))
    if pd.notna(commune) and str(commune).strip():
        adresse_parts.append(str(commune))

    adresse = " ".join(adresse_parts)

    if not adresse.strip():
        return None, None

    # Appeler l'API
    url = "https://data.geopf.fr/geocodage/search"
    params = {
        "q": adresse,
        "limit": 1
    }

    try:
        response = requests.get(url, params=params, timeout=10)
        response.raise_for_status()
        data = response.json()

        if data.get("features") and len(data["features"]) > 0:
            coords = data["features"][0]["geometry"]["coordinates"]
            return coords[0], coords[1]  # longitude, latitude
        else:
            return None, None

    except Exception as e:
        print(f"Erreur pour '{adresse}': {e}")
        return None, None


def geocoder_dataframe(df, batch_size=100, delay=0.05):
    """
    Géocode toutes les lignes d'un DataFrame par batch

    Args:
        df: DataFrame avec les colonnes adresse_numero, adresse_nom_voie, code_postal, nom_commune
        batch_size: Nombre de lignes à traiter avant de sauvegarder
        delay: Délai entre chaque requête en secondes (pour respecter la limite de 50 req/s)
    """
    total_rows = len(df)
    print(f"Géocodage de {total_rows} adresses...")
    print(f"Traitement par batch de {batch_size} lignes")

    # Initialiser les colonnes si elles n'existent pas
    if 'longitude' not in df.columns:
        df['longitude'] = None
    if 'latitude' not in df.columns:
        df['latitude'] = None

    # Créer un fichier de sauvegarde
    backup_file = "geocodage_backup.csv"

    # Compter les lignes déjà géocodées
    lignes_a_geocoder = df[df['longitude'].isna()].index
    print(f"{len(lignes_a_geocoder)} adresses à géocoder")

    # Barre de progression
    with tqdm(total=len(lignes_a_geocoder), desc="Géocodage") as pbar:
        batch_count = 0

        for idx in lignes_a_geocoder:
            row = df.loc[idx]

            # Géocoder l'adresse
            lon, lat = geocoder_adresse(
                row['adresse_numero'],
                row['adresse_nom_voie'],
                row['code_postal'],
                row['nom_commune']
            )

            # Mettre à jour le DataFrame
            df.at[idx, 'longitude'] = lon
            df.at[idx, 'latitude'] = lat

            batch_count += 1
            pbar.update(1)

            # Sauvegarder périodiquement
            if batch_count % batch_size == 0:
                df.to_csv(backup_file, index=False)
                print(f"\n✓ Backup sauvegardé ({batch_count} lignes traitées)")

            # Respecter la limite de 50 requêtes par seconde
            time.sleep(delay)

    # Sauvegarde finale
    df.to_csv(backup_file, index=False)
    print(f"\n✓ Géocodage terminé!")

    # Statistiques
    geocoded = df['longitude'].notna().sum()
    print(f"\nRésultats:")
    print(f"  - Adresses géocodées: {geocoded} / {total_rows} ({geocoded/total_rows*100:.1f}%)")
    print(f"  - Adresses non trouvées: {total_rows - geocoded}")

    return df

In [29]:
df_geocoded = geocoder_dataframe(
    df,
    batch_size=1000,  # Sauvegarde tous les 100 géocodages
    delay=0.1       # 0.05s entre chaque requête = ~20 req/s (bien en dessous de la limite)
)

Géocodage de 672749 adresses...
Traitement par batch de 1000 lignes
8580 adresses à géocoder

Géocodage:   3%|▎         | 254/8580 [01:12<2:05:14,  1.11it/s]

Erreur pour '7.0 RUE DU GENERAL LECLERC 91220.0 Brétigny-sur-Orge': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=7.0+RUE+DU+GENERAL+LECLERC+91220.0+Br%C3%A9tigny-sur-Orge&limit=1

Géocodage:   7%|▋         | 572/8580 [02:34<2:01:19,  1.10it/s]

Erreur pour '45.0 RUE DU DOCTEUR VAILLANT 91700.0 Sainte-Geneviève-des-Bois': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=45.0+RUE+DU+DOCTEUR+VAILLANT+91700.0+Sainte-Genevi%C3%A8ve-des-Bois&limit=1

Géocodage:   7%|▋         | 576/8580 [02:37<2:14:40,  1.01s/it]

Erreur pour '52.0 RUE DE LA DEMI LUNE 93100.0 Montreuil': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=52.0+RUE+DE+LA+DEMI+LUNE+93100.0+Montreuil&limit=1

Géocodage:  12%|█▏        | 1000/8580 [04:36<29:28,  4.29it/s]

✓ Backup sauvegardé (1000 lignes traitées)

Géocodage:  12%|█▏        | 1001/8580 [04:58<13:39:01,  6.48s/it]

Erreur pour '15.0 RUE FRAIZIER 93210.0 Saint-Denis': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=15.0+RUE+FRAIZIER+93210.0+Saint-Denis&limit=1

Géocodage:  13%|█▎        | 1085/8580 [05:21<2:24:40,  1.16s/it]

Erreur pour '4.0 RUE DE LA CROIX DE GERVILLE 91450.0 Soisy-sur-Seine': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=4.0+RUE+DE+LA+CROIX+DE+GERVILLE+91450.0+Soisy-sur-Seine&limit=1

Géocodage:  14%|█▎        | 1160/8580 [05:42<1:19:32,  1.55it/s]

Erreur pour '26.0 RUE NUNGESSER ET COLI 93380.0 Pierrefitte-sur-Seine': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=26.0+RUE+NUNGESSER+ET+COLI+93380.0+Pierrefitte-sur-Seine&limit=1

Géocodage:  16%|█▌        | 1363/8580 [06:46<1:40:01,  1.20it/s]

Erreur pour '182.0 LA MUSSINE 77820.0 Le Châtelet-en-Brie': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=182.0+LA+MUSSINE+77820.0+Le+Ch%C3%A2telet-en-Brie&limit=1

Géocodage:  20%|█▉        | 1709/8580 [08:25<1:37:13,  1.18it/s]

Erreur pour '43.0 RUE ANATOLE FRANCE 94490.0 Ormesson-sur-Marne': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=43.0+RUE+ANATOLE+FRANCE+94490.0+Ormesson-sur-Marne&limit=1

Géocodage:  22%|██▏       | 1879/8580 [09:08<1:29:50,  1.24it/s]

Erreur pour '96.0 RUE HENRI PROU 78340.0 Les Clayes-sous-Bois': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=96.0+RUE+HENRI+PROU+78340.0+Les+Clayes-sous-Bois&limit=1

Géocodage:  23%|██▎       | 2000/8580 [09:34<22:07,  4.96it/s]

✓ Backup sauvegardé (2000 lignes traitées)

Géocodage:  24%|██▎       | 2024/8580 [09:57<1:39:47,  1.09it/s]

Erreur pour '10.0 RUE DE VAUX 91470.0 Forges-les-Bains': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=10.0+RUE+DE+VAUX+91470.0+Forges-les-Bains&limit=1

Géocodage:  25%|██▍       | 2143/8580 [10:33<1:34:56,  1.13it/s]

Erreur pour '17.0 RTE DU MESLE 78113.0 Adainville': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=17.0+RTE+DU+MESLE+78113.0+Adainville&limit=1

Géocodage:  26%|██▌       | 2220/8580 [11:02<3:09:16,  1.79s/it]

Erreur pour '131.0 RUE DE FLEURY 92140.0 Clamart': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=131.0+RUE+DE+FLEURY+92140.0+Clamart&limit=1

Géocodage:  26%|██▌       | 2223/8580 [11:05<2:24:36,  1.36s/it]

Erreur pour '3.0 RUE DU CORBILLON 93200.0 Saint-Denis': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=3.0+RUE+DU+CORBILLON+93200.0+Saint-Denis&limit=1

Géocodage:  27%|██▋       | 2322/8580 [11:39<1:59:08,  1.14s/it]

Erreur pour '5.0 RUE DU BEL AIR 78930.0 Guerville': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=5.0+RUE+DU+BEL+AIR+78930.0+Guerville&limit=1

Géocodage:  27%|██▋       | 2330/8580 [11:43<1:33:44,  1.11it/s]

Erreur pour '12.0 RUE DE LA COURANDAINE 77169.0 Boissy-le-Châtel': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=12.0+RUE+DE+LA+COURANDAINE+77169.0+Boissy-le-Ch%C3%A2tel&limit=1

Géocodage:  27%|██▋       | 2350/8580 [11:52<2:22:40,  1.37s/it]

Erreur pour '14.0 RUE DE LA CHATAIGNERAIE 91470.0 Forges-les-Bains': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=14.0+RUE+DE+LA+CHATAIGNERAIE+91470.0+Forges-les-Bains&limit=1

Géocodage:  30%|██▉       | 2561/8580 [13:11<1:28:47,  1.13it/s]

Erreur pour '45.0 RTE DE FONTAINE LE PORT 77820.0 Le Châtelet-en-Brie': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=45.0+RTE+DE+FONTAINE+LE+PORT+77820.0+Le+Ch%C3%A2telet-en-Brie&limit=1

Géocodage:  32%|███▏      | 2770/8580 [14:18<1:21:16,  1.19it/s]

Erreur pour '17.0 VLA DU BELVEDERE 93380.0 Pierrefitte-sur-Seine': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=17.0+VLA+DU+BELVEDERE+93380.0+Pierrefitte-sur-Seine&limit=1

Géocodage:  35%|███▍      | 3000/8580 [15:37<30:02,  3.10it/s]

✓ Backup sauvegardé (3000 lignes traitées)

Géocodage:  39%|███▉      | 3380/8580 [17:48<1:16:25,  1.13it/s]

Erreur pour '7.0 RUE PIERRE BROSSOLETTE 95270.0 Asnières-sur-Oise': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=7.0+RUE+PIERRE+BROSSOLETTE+95270.0+Asni%C3%A8res-sur-Oise&limit=1

Géocodage:  42%|████▏     | 3611/8580 [18:53<1:10:16,  1.18it/s]

Erreur pour '17.0 IMP DE L'ANGUILLE 77870.0 Vulaines-sur-Seine': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=17.0+IMP+DE+L%27ANGUILLE+77870.0+Vulaines-sur-Seine&limit=1

Géocodage:  47%|████▋     | 4000/8580 [20:45<22:05,  3.45it/s]

✓ Backup sauvegardé (4000 lignes traitées)

Géocodage:  48%|████▊     | 4137/8580 [21:45<1:08:14,  1.09it/s]

Erreur pour '9004.0 RTE NATIONALE 1 95460.0 Ézanville': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=9004.0+RTE+NATIONALE+1+95460.0+%C3%89zanville&limit=1

Géocodage:  49%|████▊     | 4165/8580 [21:57<1:08:30,  1.07it/s]

Erreur pour '60.0 RUE JEAN DE LA FONTAINE 78000.0 Versailles': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=60.0+RUE+JEAN+DE+LA+FONTAINE+78000.0+Versailles&limit=1

Géocodage:  52%|█████▏    | 4503/8580 [23:43<1:29:55,  1.32s/it]

Erreur pour '18.0 RUE DE L AVENIR 78400.0 Chatou': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=18.0+RUE+DE+L+AVENIR+78400.0+Chatou&limit=1

Géocodage:  53%|█████▎    | 4521/8580 [23:50<1:06:49,  1.01it/s]

Erreur pour '64.0 RUE DU LNT GEORGES KEISER 95110.0 Sannois': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=64.0+RUE+DU+LNT+GEORGES+KEISER+95110.0+Sannois&limit=1

Géocodage:  53%|█████▎    | 4560/8580 [24:02<56:57,  1.18it/s]

Erreur pour '1.0 RUE DU LAVOIR 78930.0 Guerville': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=1.0+RUE+DU+LAVOIR+78930.0+Guerville&limit=1

Géocodage:  54%|█████▍    | 4623/8580 [24:20<1:03:38,  1.04it/s]

Erreur pour '10.0 RUE LEON JOUHAUX 93420.0 Villepinte': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=10.0+RUE+LEON+JOUHAUX+93420.0+Villepinte&limit=1

Géocodage:  56%|█████▌    | 4808/8580 [25:19<54:18,  1.16it/s]

Erreur pour '14.0 RUE DES ERABLES 78711.0 Mantes-la-Ville': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=14.0+RUE+DES+ERABLES+78711.0+Mantes-la-Ville&limit=1

Géocodage:  58%|█████▊    | 4992/8580 [26:12<57:22,  1.04it/s]

Erreur pour '18.0 RUE PIERRE CURIE 78930.0 Guerville': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=18.0+RUE+PIERRE+CURIE+78930.0+Guerville&limit=1

Géocodage:  58%|█████▊    | 5001/8580 [26:28<4:24:45,  4.44s/it]

✓ Backup sauvegardé (5000 lignes traitées)

Géocodage:  59%|█████▉    | 5051/8580 [26:46<55:51,  1.05it/s]

Erreur pour '2.0 RUE PASCAL 78960.0 Voisins-le-Bretonneux': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=2.0+RUE+PASCAL+78960.0+Voisins-le-Bretonneux&limit=1

Géocodage:  63%|██████▎   | 5375/8580 [28:17<43:55,  1.22it/s]

Erreur pour '2.0 RUE DE LA COTE ST REMY 95240.0 Cormeilles-en-Parisis': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=2.0+RUE+DE+LA+COTE+ST+REMY+95240.0+Cormeilles-en-Parisis&limit=1

Géocodage:  65%|██████▍   | 5568/8580 [29:09<1:07:58,  1.35s/it]

Erreur pour '49.0 RUE LA FAYETTE 91700.0 Sainte-Geneviève-des-Bois': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=49.0+RUE+LA+FAYETTE+91700.0+Sainte-Genevi%C3%A8ve-des-Bois&limit=1

Géocodage:  65%|██████▌   | 5603/8580 [29:22<31:30,  1.57it/s]

Erreur pour '44.0 DOM DE VILLEJUST 91140.0 Villejust': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=44.0+DOM+DE+VILLEJUST+91140.0+Villejust&limit=1

Géocodage:  66%|██████▌   | 5628/8580 [29:30<49:14,  1.00s/it]

Erreur pour '135.0 AV LENINE 93380.0 Pierrefitte-sur-Seine': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=135.0+AV+LENINE+93380.0+Pierrefitte-sur-Seine&limit=1

Géocodage:  67%|██████▋   | 5715/8580 [29:56<39:34,  1.21it/s]

Erreur pour '37.0 RTE DE LA BUTTE ROUGE 77510.0 Hondevilliers': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=37.0+RTE+DE+LA+BUTTE+ROUGE+77510.0+Hondevilliers&limit=1

Géocodage:  70%|██████▉   | 6000/8580 [31:17<11:09,  3.85it/s]

✓ Backup sauvegardé (6000 lignes traitées)

Géocodage:  71%|███████   | 6110/8580 [32:03<36:05,  1.14it/s]

Erreur pour '19.0 RUE D ALESIA 93000.0 Bobigny': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=19.0+RUE+D+ALESIA+93000.0+Bobigny&limit=1

Géocodage:  73%|███████▎  | 6253/8580 [32:45<24:16,  1.60it/s]

Erreur pour '19.0 RUE D ALESIA 93000.0 Bobigny': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=19.0+RUE+D+ALESIA+93000.0+Bobigny&limit=1

Géocodage:  74%|███████▍  | 6346/8580 [33:11<33:18,  1.12it/s]

Erreur pour '19.0 RUE D ALESIA 93000.0 Bobigny': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=19.0+RUE+D+ALESIA+93000.0+Bobigny&limit=1

Géocodage:  80%|███████▉  | 6828/8580 [35:15<34:51,  1.19s/it]

Erreur pour '25.0 BD DE VANVES 92320.0 Châtillon': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=25.0+BD+DE+VANVES+92320.0+Ch%C3%A2tillon&limit=1

Géocodage:  81%|████████▏ | 6987/8580 [36:05<23:24,  1.13it/s]

Erreur pour '51.0 RUE DE LA REPUBLIQUE 91150.0 Étampes': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=51.0+RUE+DE+LA+REPUBLIQUE+91150.0+%C3%89tampes&limit=1

Géocodage:  82%|████████▏ | 7000/8580 [36:08<06:12,  4.24it/s]

✓ Backup sauvegardé (7000 lignes traitées)

Géocodage:  82%|████████▏ | 7077/8580 [36:44<24:54,  1.01it/s]

Erreur pour '7.0 RUE DES MERISIERS 78930.0 Guerville': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=7.0+RUE+DES+MERISIERS+78930.0+Guerville&limit=1

Géocodage:  83%|████████▎ | 7091/8580 [36:51<26:30,  1.07s/it]

Erreur pour '34.0 RUE HOCHE 91260.0 Juvisy-sur-Orge': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=34.0+RUE+HOCHE+91260.0+Juvisy-sur-Orge&limit=1

Géocodage:  88%|████████▊ | 7582/8580 [39:23<12:51,  1.29it/s]

Erreur pour '15.0 BD JULES VALLES 91100.0 Corbeil-Essonnes': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=15.0+BD+JULES+VALLES+91100.0+Corbeil-Essonnes&limit=1

Géocodage:  89%|████████▉ | 7618/8580 [39:40<14:48,  1.08it/s]

Erreur pour '12.0 RUE CHAMPLAIN 91170.0 Viry-Châtillon': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=12.0+RUE+CHAMPLAIN+91170.0+Viry-Ch%C3%A2tillon&limit=1

Géocodage:  89%|████████▉ | 7669/8580 [39:56<11:47,  1.29it/s]

Erreur pour '3.0 ALL GUYNEMER 93330.0 Neuilly-sur-Marne': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=3.0+ALL+GUYNEMER+93330.0+Neuilly-sur-Marne&limit=1

Géocodage:  92%|█████████▏| 7932/8580 [41:04<09:18,  1.16it/s]

Erreur pour '25.0 RUE BLAISE PASCAL 91120.0 Palaiseau': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=25.0+RUE+BLAISE+PASCAL+91120.0+Palaiseau&limit=1

Géocodage:  93%|█████████▎| 7955/8580 [41:15<08:40,  1.20it/s]

Erreur pour '7.0 RUE DES ABRICOTIERS 91600.0 Savigny-sur-Orge': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=7.0+RUE+DES+ABRICOTIERS+91600.0+Savigny-sur-Orge&limit=1

Géocodage:  93%|█████████▎| 8000/8580 [41:28<01:58,  4.91it/s]

✓ Backup sauvegardé (8000 lignes traitées)

Géocodage:  94%|█████████▍| 8107/8580 [42:14<07:19,  1.08it/s]

Erreur pour '4.0 RUE RENARD BENOIT 78970.0 Mézières-sur-Seine': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=4.0+RUE+RENARD+BENOIT+78970.0+M%C3%A9zi%C3%A8res-sur-Seine&limit=1

Géocodage:  95%|█████████▌| 8171/8580 [42:36<06:32,  1.04it/s]

Erreur pour '8.0 RES LES FOURNEAUX 78970.0 Mézières-sur-Seine': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=8.0+RES+LES+FOURNEAUX+78970.0+M%C3%A9zi%C3%A8res-sur-Seine&limit=1

Géocodage:  98%|█████████▊| 8434/8580 [43:48<01:59,  1.22it/s]

Erreur pour '11.0 RUE RICHARD VIAN 91530.0 Saint-Chéron': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=11.0+RUE+RICHARD+VIAN+91530.0+Saint-Ch%C3%A9ron&limit=1

Géocodage: 100%|██████████| 8580/8580 [44:22<00:00,  3.22it/s]

✓ Géocodage terminé!

Résultats:
  - Adresses géocodées: 672445 / 672749 (100.0%)
  - Adresses non trouvées: 304

In [30]:
df_geocoded.head()

,date_mutation,nature_mutation,valeur_fonciere,adresse_numero,adresse_nom_voie,adresse_code_voie,code_postal,code_commune,nom_commune,code_departement,...,commune_part_admin_sante,commune_etablissements_par_menage,commune_taux_etablissements_10_plus,commune_sante_score_2013_commune,commune_education_score_2013_commune,commune_revenu_score_2013_commune,commune_idh2_2013_commune,commune_taux_criminalite_moyen,commune_taux_croissance_pop,commune_densite_pop
0,2021-01-01,Vente,169500.0,28.0,ALL HOCHE,4440,92130.0,92040,Issy-les-Moulineaux,92,...,0.090161,0.075901,0.254014,0.700824,0.835437,0.704796,0.747019,0.376209,1.045371,16106.117647
1,2021-01-02,Vente,415000.0,109.0,RUE DES COURLIS,1570,95100.0,95018,Argenteuil,95,...,0.085686,0.071492,0.182996,0.567644,0.364296,0.331115,0.421018,0.561570,0.784827,6400.116144
2,2021-01-02,Vente,415000.0,109.0,RUE DES COURLIS,1570,95100.0,95018,Argenteuil,95,...,0.085686,0.071492,0.182996,0.567644,0.364296,0.331115,0.421018,0.561570,0.784827,6400.116144
3,2021-01-02,Vente,512000.0,97.0,RUE DE CHARONNE,1888,75011.0,75111,Paris 11e Arrondissement,75,...,0.067020,0.131609,0.145909,0.680558,0.851424,0.607516,0.713166,0.996164,-1.129705,39957.220708
4,2021-01-02,Vente,512000.0,97.0,RUE DE CHARONNE,1888,75011.0,75111,Paris 11e Arrondissement,75,...,0.067020,0.131609,0.145909,0.680558,0.851424,0.607516,0.713166,0.996164,-1.129705,39957.220708

In [32]:
df_without_lat_geocod = df_geocoded[df_geocoded['latitude'].isnull()]
df_without_lat_geocod

,date_mutation,nature_mutation,valeur_fonciere,adresse_numero,adresse_nom_voie,adresse_code_voie,code_postal,code_commune,nom_commune,code_departement,...,commune_part_admin_sante,commune_etablissements_par_menage,commune_taux_etablissements_10_plus,commune_sante_score_2013_commune,commune_education_score_2013_commune,commune_revenu_score_2013_commune,commune_idh2_2013_commune,commune_taux_criminalite_moyen,commune_taux_croissance_pop,commune_densite_pop
1809,2021-01-08,Vente,243000.0,33.0,PAS MAURICE,6130,93380.0,93059,Pierrefitte-sur-Seine,93,...,0.072340,0.064359,0.124823,0.591285,0.252541,0.141425,0.328417,NaN,1.584453,8887.390029
2751,2021-01-11,Vente,448500.0,5233.0,LES GALLIONNETS,B067,78630.0,78466,Orgeval,78,...,0.065823,0.156933,0.200000,0.750462,0.799138,0.812501,0.787367,0.358735,1.141541,408.545336
3564,2021-01-13,Vente,68000.0,9.0,RUE TALMA,9121,93380.0,93059,Pierrefitte-sur-Seine,93,...,0.072340,0.064359,0.124823,0.591285,0.252541,0.141425,0.328417,NaN,1.584453,8887.390029
3989,2021-01-14,Vente,246377.0,1.0,VC DES ALLIES,0033,94600.0,94022,Choisy-le-Roi,94,...,0.094128,0.058466,0.162349,0.611073,0.474677,0.400950,0.495567,0.566695,1.465068,8348.250460
4609,2021-01-15,Vente,260869.0,1.0,VC DES ALLIES,0033,94600.0,94022,Choisy-le-Roi,94,...,0.094128,0.058466,0.162349,0.611073,0.474677,0.400950,0.495567,0.566695,1.465068,8348.250460
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
549610,2024-06-14,Vente,280000.0,8.0,RES LES FOURNEAUX,A100,78970.0,78402,Mézières-sur-Seine,78,...,0.144737,0.051287,0.144737,0.655672,0.472022,0.589140,0.572278,0.180551,0.580753,362.380038
558938,2024-07-05,Vente,220000.0,8.0,RUE BROHAN,0685,93380.0,93059,Pierrefitte-sur-Seine,93,...,0.072340,0.064359,0.124823,0.591285,0.252541,0.141425,0.328417,NaN,1.388964,9191.788856
563259,2024-07-16,Vente,170000.0,37.0,RUE PIERRE DEGEYTER,7171,93380.0,93059,Pierrefitte-sur-Seine,93,...,0.072340,0.064359,0.124823,0.591285,0.252541,0.141425,0.328417,NaN,1.388964,9191.788856
569761,2024-07-31,Vente,300000.0,9.0,AV GUIARD,4185,93380.0,93059,Pierrefitte-sur-Seine,93,...,0.072340,0.064359,0.124823,0.591285,0.252541,0.141425,0.328417,NaN,1.388964,9191.788856
610796,2024-12-02,Vente,162000.0,11.0,RUE RICHARD VIAN,0240,91530.0,91540,Saint-Chéron,91,...,0.138614,0.047380,0.148515,0.659312,0.469415,0.574009,0.567579,0.201480,1.180032,460.139860

In [35]:
df_full_geocod = geocoder_dataframe(
    df_geocoded,
    batch_size=1000,  # Sauvegarde tous les 100 géocodages
    delay=0.1       # 0.05s entre chaque requête = ~20 req/s (bien en dessous de la limite)
)

Géocodage de 672749 adresses...
Traitement par batch de 1000 lignes
300 adresses à géocoder

Géocodage:  51%|█████     | 152/300 [00:45<02:09,  1.14it/s]

Erreur pour '9004.0 RTE NATIONALE 1 95460.0 Ézanville': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=9004.0+RTE+NATIONALE+1+95460.0+%C3%89zanville&limit=1

Géocodage:  67%|██████▋   | 202/300 [01:02<01:48,  1.11s/it]

Erreur pour '7.0 RUE RACHEL 93380.0 Pierrefitte-sur-Seine': 504 Server Error: Gateway Timeout for url: https://data.geopf.fr/geocodage/search?q=7.0+RUE+RACHEL+93380.0+Pierrefitte-sur-Seine&limit=1

Géocodage: 100%|██████████| 300/300 [01:39<00:00,  3.00it/s]

✓ Géocodage terminé!

Résultats:
  - Adresses géocodées: 672493 / 672749 (100.0%)
  - Adresses non trouvées: 256

In [38]:
df_full_geocod.shape

(672749, 54)

In [7]:
df_full_geocod["latitude"].isnull().sum()

NameError: name 'df_full_geocod' is not defined